language: node_js
node_js:
- '6.9'
- '7.1'
sudo: false
cache:
  directories:
  - node_modules
before_install:
# Update Node.js modules
- test ! -d node_modules || npm prune
- test ! -d node_modules || npm rebuild
script:
- npm run-script lint
- npm run-script test-travis
deploy:
  provider: npm
  email: bgjehu@me.com
  api_key:
    secure: iHaesoeCg0633+yF9K71enkjYP6xxzbHehNrkR51N44DQJvXxamvmwN1n973Q9uw8mxsWG6pI8xIetx0IE+ZhnEZK1oT6q6jfjoueQN2NxGeOVgsxuzViV0TwLF+l+OUSk0qsICL9myqPcR69m2WxF8sZptQV+9eReRuDtv+3IkWdaSZO+OCxzYAggIgfGi+zm+me5Gek+3XUiLmaNjMEs9espOrxe9dhe+mfnF4w7rw4lceyaWpFmDJRrKDgtiCioPXTgvWXAoHMclY7KDE8yt6Y4W0phdImYwpcgLbSq7TSZDuHB/fvrOfG13uhjnyoOiVSCVBEVo23eHzFGOBEY7x54hPKdIqdhQMRHcWIKrYyvNYvi4HiqSZTIu+olyRC7/X58EP2aBvZp9mEuK41F09tJY266ItSCG5bIVu/U81tXZXoMDK0gKujjjxgO/Ioj+7HRGm18BzXDiFZu3DvTDopnmPGma2awZ6JD3IU/QXHSjiIhzOCbcaa9YYzgfD3xvZDKWtp4wfiB8lO/SUpS8OYQwEhihffHqhIlvUIdR5bCdtmDjcR4aHO33XygB7BTrQaiYQCvwdj7BUjaPRDmVmr1qlqmaT6T4BJ7qJJoB2aB1oJIDibKMtiVjlUn2SDotwFC0TjbJKB8HK/3G3cC76KGJOLcYNCV1sS2G9kfc=
  on:
    tags: true
    repo: bgjehu/map-resolver
