language: node_js
node_js:
- '6.9'
- '7.1'
sudo: false
cache:
  directories:
  - node_modules
before_install:
# Update Node.js modules
- test ! -d node_modules || npm prune
- test ! -d node_modules || npm rebuild
script:
- npm run-script lint
- npm run-script test-travis
deploy:
  provider: npm
  email: bgjehu@me.com
  api_key:
    secure: iijuoPhA4tG+9ygkNLau5VZ6jge6pb5R2v7eW5npWAS1tFj3M4wU/ArO1pP9zQSgN2IL+xY1UvDqtGa/1vrFTl4w7o+fOHBjBdaNt2HIjFFutLQ7+Cdv79vkZo4xWA6QnE+MjRmSf8Kwvx9yYW21EK8BvMgEq4frfS/aGFnKAgY+I6Z5JcA7zqGJYeZ/Z94Jb2xokmu2scPw37ycQoFXSAmmTsT9OvouOAFBKmWjS/HQQE6Aeo4oXF76VAHjk6+R4zjsLNkDrPdUEUSiKuO4xP8dbBseNmwGQrgTOC0svwOI2FHv4KDuPTeQ7BWkdYM20BDEcHC5fQELS/YR0NjCyPeZImzKNzTs3n554pAFFSUWojOsD/Kw6J/sqd9KWgJEM2K4tJ0BAf7b08y6fXJupmhTDXlV3+dI5+zNWfpvrZkxFnZM5DChkyRkl0NWMNLRTPz8EU9/NNlyUv47H4PfPg7wENqZLKgCO3zfaFZnSyzWndGrWfFeoqCqox/Ckcns9Usy9KHD7O4qk31v4ctDDC36PVP5cbsKwTJUC12Pxo6zwOpPD3WKkFsWPdSkVjmgzx4Tr2zmj+RrWM9gL3k6ChdoEQ4VK7Mxh7KEBjAVkAQRdM4f7dqPQTLeeL+yzQTBBfmSvcEHAT1IVaO+zwZ3Mvkqf4j5Y6PiO8vqJYZW2jA=
  on:
    tags: true
    repo: bgjehu/map-resolver
