language: node_js
node_js:
- '6.9'
- '7.1'
sudo: false
cache:
  directories:
  - node_modules
script:
- npm run-script lint
- npm run-script test-travis
deploy:
  provider: npm
  email: bgjehu@me.com
  api_key:
    secure: T2cI3rRHR/bi/i34cLPi/g9W/aR1lwHEmNU8A+nR48Op1JclK7YeqNatuetPMwPpCQhjIkFJTCM8xjWQqU77r3xjNzPgbvQBF4Tp5jinpTasQZI3zSxe2qAjJ5XOYC+/IculGat4hBBSDTWqs5EIDz1P4i2Rhz1bNd+roi+0X2mo/gIAjYA9fr8Ay+nhaR6WNJsbxF8EqbghJjuyhfmypZnRR2OCUNHpibiJul8BguT/zd3xZwVyoB2u7ACSCmIMdmfY0IKbYGNOXdGIJ/Ktbmv6Pli/a2draX4Shwt1+Hy71ma0CFgSLOzE85B0/+Xli6XofbpCXRhk6jbGX9fr3zfc5/fVQixc2/lxK3fUaKFxgTQyqbnsdRo2iWk2oJ9Tu9/RtAhMRmmjtJMcnGkS+f8WdqRa/ZIwqloU21Z4NSP2UToMzmUz6j28OcKU9jeC5f1wKF2bNPaQmrHyJa2Y1BFtPwRI3OKUcnbzLIoKOldLX3KD4oWT8fQyXpAq764GxsJudZST50kr3hWZwMOe22Qajz3l6K9Zwz/45QJTT1oeVyi4RrKMUzgDxgErja5qwyAshDp1sOHMAtGGo/pPBv09ttNGEiClRYowK2nvcm8LmrvWmxGfc+mAOlIzQWGTVLQXfaGLmo6CxWTGOPGiMVQDOzx9j31M/9VcacwU6Qk=
  on:
    tags: true
    repo: bgjehu/map-resolver
